In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("data/raw/ecommerce_purchase_intent.csv")

df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Converted
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,June,1,2,1,1,Returning_Visitor,False,1
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,May,2,1,8,12,Returning_Visitor,False,0
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,Mar,1,2,1,3,New_Visitor,True,0
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,Dec,1,1,1,2,Returning_Visitor,True,0
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,Mar,2,1,2,5,Returning_Visitor,False,0

In [3]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Converted                  0
dtype: int64

In [4]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [5]:
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Converted                    int64
dtype: object

In [6]:
X = df.drop("Converted", axis=1)

y = df["Converted"]

In [7]:
categorical_cols = X.select_dtypes(include=["object"]).columns

categorical_cols

Index(['Month', 'VisitorType'], dtype='object')

In [8]:
le = LabelEncoder()

for col in categorical_cols:
    X[col] = le.fit_transform(X[col])

In [9]:
X.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,4,1,2,1,1,2,False
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,6,2,1,8,12,2,False
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,5,1,2,1,3,0,True
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,1,1,1,1,2,2,True
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,5,2,1,2,5,2,False

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [11]:
print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels  :", y_test.shape)

Training Features: (9600, 17)
Testing Features : (2400, 17)
Training Labels : (9600,)
Testing Labels  : (2400,)

In [13]:
processed_train = X_train.copy()
processed_train["Converted"] = y_train

processed_test = X_test.copy()
processed_test["Converted"] = y_test

processed_train.to_csv("data/processed/train.csv", index=False)
processed_test.to_csv("data/processed/test.csv", index=False)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!